### ISSUE TITLE
Flaky testUserIDSearchOneResult?

### ISSUE THREAD

**Issue by lenaqr** [learning-unlimited/ESP-Website#1835]
```
ERROR: testUserIDSearchOneResult (esp.program.tests.ViewUserInfoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/learning-unlimited/ESP-Website/esp/esp/program/tests.py", line 141, in testUserIDSearchOneResult
    self.assertStringContains(response['location'], "/manage/userview?username=adminuser124353")
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/http/response.py", line 208, in __getitem__
    return self._headers[header.lower()][1]
KeyError: 'location'
```

(https://travis-ci.org/learning-unlimited/ESP-Website/builds/87389625)

May have been introduced in 1.8?

**Comment by mgersh** [comment]
I think this was caused by #1561. As far as I can tell, response['location'] only exists when there's a redirect. If I'm correct about that, then this test will fail whenever the admin's id is contained in the user's first name. I'm not sure about this, though, because it seems like we should have seen this before if that were the case.

**Comment by benjaminjkraft** [comment]
This failed again on the check for #1853, so it's definitely flaky.

**Comment by vipulpandey21** [comment]
Hi Mr. Will @willgearty, I'd like to work on this issue if it's still open. It appears related to testing, and I'm currently exploring the regression test expansion idea for GSoC, so investigating this and potentially adding a regression test would fit well with that work.
