### ISSUE TITLE
some email thing breaks on non-ascii

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#2625]
Yale's dbmail_cron was failing with this:
```
[2018-10-06 15:02:52,873 esp.dbmail_cron:52] ERROR: 'ascii' codec can't encode character u'\u2014' in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "/lu/sites/yale/esp/dbmail_cron.py", line 47, in <module>
    process_messages()
  File "/lu/sites/yale/esp/esp/dbmail/cronmail.py", line 76, in process_messages
    message.process()
  File "/lu/sites/yale/env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/lu/sites/yale/esp/esp/dbmail/models.py", line 325, in process
    msgtext = self.parseSmartText(self.msgtext, user)
  File "/lu/sites/yale/esp/esp/dbmail/models.py", line 236, in parseSmartText
    return template.render(context)
  File "/lu/sites/yale/env/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/lu/sites/yale/env/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/lu/sites/yale/env/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/lu/sites/yale/env/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/lu/sites/yale/env/lib/python2.7/site-packages/django/template/base.py", line 959, in render
    output = self.filter_expression.resolve(context)
  File "/lu/sites/yale/env/lib/python2.7/site-packages/django/template/base.py", line 648, in resolve
    obj = self.var.resolve(context)
  File "/lu/sites/yale/env/lib/python2.7/site-packages/django/template/base.py", line 789, in resolve
    value = self._resolve_lookup(context)
  File "/lu/sites/yale/env/lib/python2.7/site-packages/django/template/base.py", line 827, in _resolve_lookup
    current = getattr(current, bit)
  File "/lu/sites/yale/esp/esp/dbmail/models.py", line 116, in __getattribute__
    return obj.get_msg_vars(self._user, key)
  File "/lu/sites/yale/esp/esp/program/models/__init__.py", line 339, in get_msg_vars
    retVal = module.get_msg_vars(user, key)
  File "/lu/sites/yale/esp/esp/program/modules/handlers/programprintables.py", line 725, in get_msg_vars
    return ProgramPrintables.getSchedule(self.program, user, u'Teacher')
  File "/lu/sites/yale/esp/esp/program/modules/handlers/programprintables.py", line 827, in getSchedule
    cls.title())
  File "/lu/sites/yale/env/lib/python2.7/site-packages/django/utils/html.py", line 101, in format_html
    return mark_safe(format_string.format(*args_safe, **kwargs_safe))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 6: ordinal not in range(128)
```

I ended up just deleting the offending message requests, but we should fix this for future uses.

**Comment by benjaminjkraft** [comment]
For reference I think it is the `{{program.teacher_schedule}}` in this MR that was failing: https://yale.learningu.org/admin/dbmail/messagerequest/1021/

**Comment by benjaminjkraft** [comment]
Oops lol apparently this was #2549 and it just wasn't in sr10.
